version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.43.0
    ports:
      - 9000:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
