version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 9001:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
