version: '3'

x-kong-config:
  &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-postgres}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: kong-database
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
  
services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    ports:
      - "5432:5432"
    networks:
    - kong-net

  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong:latest
    environment:
      <<: *kong-env
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"      
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr      
    secrets:
      - kong_postgres_password    
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8002:8002"
    restart: on-failure:5    
    volumes:      
      - ./config:/opt/kong
    networks:
      - kong-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - kong-database
      - kong-migration

  konga:
    image: pantsel/konga:latest
    environment:
      NO_AUTH: true
      NODE_ENV: production
    secrets:
      - konga_token_secret    
    ports:
      - "1337:1337"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - kong
      - kong-database
      - kong-migration
    networks:
     - kong-net

networks:
  kong-net:
    external: false

secrets:
  konga_token_secret:
    file: ./TOKEN_SECRET
  kong_postgres_password:
    file: ./POSTGRES_PASSWORD